# Global settings applied to the whole site.
[build]
publish = "dist"
command = "npm run build:staging"

[context.production]
  command = "npm run build:prod"

[context.branch]
  command = "npm run build:staging"

